project_id = "dwinqajspowvbkvzbbbn"

[functions.send-notifications]
verify_jwt = false

[functions.create-backup]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = true

[functions.backup-attachments]
verify_jwt = false

[functions.backup-to-gdrive]
verify_jwt = false
