ALTER POLICY "Allow DELETE on contractors based on permissions" ON public.contractors TO authenticated;
ALTER POLICY "Allow INSERT on contractors based on permissions" ON public.contractors TO authenticated;
ALTER POLICY "Allow SELECT on contractors based on permissions" ON public.contractors TO authenticated;
ALTER POLICY "Allow UPDATE on contractors based on permissions" ON public.contractors TO authenticated;
ALTER POLICY "Allow DELETE on suppliers based on permissions" ON public.suppliers TO authenticated;
ALTER POLICY "Allow INSERT on suppliers based on permissions" ON public.suppliers TO authenticated;
ALTER POLICY "Allow SELECT on suppliers based on permissions" ON public.suppliers TO authenticated;
ALTER POLICY "Allow UPDATE on suppliers based on permissions" ON public.suppliers TO authenticated;
ALTER POLICY "Users can insert their own profile" ON public.profiles TO authenticated;
ALTER POLICY "Users can update their own profile" ON public.profiles TO authenticated;
ALTER POLICY "Users can view their own profile" ON public.profiles TO authenticated;
ALTER POLICY "Admin users can update company settings" ON public.company_settings TO authenticated;
ALTER POLICY "Authenticated users can view company settings" ON public.company_settings TO authenticated;
ALTER POLICY "Allow DELETE on projects based on permissions" ON public.projects TO authenticated;
ALTER POLICY "Allow INSERT on projects based on permissions" ON public.projects TO authenticated;
ALTER POLICY "Allow SELECT on projects based on permissions" ON public.projects TO authenticated;
ALTER POLICY "Allow UPDATE on projects based on permissions" ON public.projects TO authenticated;
ALTER POLICY "Allow DELETE on invoices based on permissions" ON public.invoices TO authenticated;
ALTER POLICY "Allow INSERT on invoices based on permissions" ON public.invoices TO authenticated;
ALTER POLICY "Allow SELECT on invoices based on permissions" ON public.invoices TO authenticated;
ALTER POLICY "Allow UPDATE on invoices based on permissions" ON public.invoices TO authenticated;
ALTER POLICY "Allow DELETE on maintenance_requests based on permissions" ON public.maintenance_requests TO authenticated;
ALTER POLICY "Allow INSERT on maintenance_requests based on permissions" ON public.maintenance_requests TO authenticated;
ALTER POLICY "Allow SELECT on maintenance_requests based on permissions" ON public.maintenance_requests TO authenticated;
ALTER POLICY "Allow UPDATE on maintenance_requests based on permissions" ON public.maintenance_requests TO authenticated;
ALTER POLICY "Users can insert their own notification settings" ON public.notification_settings TO authenticated;
ALTER POLICY "Users can update their own notification settings" ON public.notification_settings TO authenticated;
ALTER POLICY "Users can view their own notification settings" ON public.notification_settings TO authenticated;
ALTER POLICY "Allow DELETE on tasks based on permissions" ON public.tasks TO authenticated;
ALTER POLICY "Allow INSERT on tasks based on permissions" ON public.tasks TO authenticated;
ALTER POLICY "Allow SELECT on tasks based on permissions" ON public.tasks TO authenticated;
ALTER POLICY "Allow UPDATE on tasks based on permissions" ON public.tasks TO authenticated;
ALTER POLICY "Admin users can create backup logs" ON public.backup_logs TO authenticated;
ALTER POLICY "Admin users can view backup logs" ON public.backup_logs TO authenticated;
ALTER POLICY "Users can update their own notifications" ON public.notifications TO authenticated;
ALTER POLICY "Users can view their own notifications" ON public.notifications TO authenticated;
ALTER POLICY "Admin users can update security settings" ON public.security_settings TO authenticated;
ALTER POLICY "Admin users can view security settings" ON public.security_settings TO authenticated;
ALTER POLICY "Allow DELETE on purchases based on permissions" ON public.purchases TO authenticated;
ALTER POLICY "Allow INSERT on purchases based on permissions" ON public.purchases TO authenticated;
ALTER POLICY "Allow SELECT on purchases based on permissions" ON public.purchases TO authenticated;
ALTER POLICY "Allow UPDATE on purchases based on permissions" ON public.purchases TO authenticated;
ALTER POLICY "Allow DELETE on extracts based on permissions" ON public.extracts TO authenticated;
ALTER POLICY "Allow INSERT on extracts based on permissions" ON public.extracts TO authenticated;
ALTER POLICY "Allow SELECT on extracts based on permissions" ON public.extracts TO authenticated;
ALTER POLICY "Allow UPDATE on extracts based on permissions" ON public.extracts TO authenticated;
ALTER POLICY "Admin users can manage chart of accounts" ON public.chart_of_accounts TO authenticated;
ALTER POLICY "Authenticated users can view chart of accounts" ON public.chart_of_accounts TO authenticated;
ALTER POLICY "Users can create journal entries" ON public.journal_entries TO authenticated;
ALTER POLICY "Users can manage journal entry lines" ON public.journal_entry_lines TO authenticated;
ALTER POLICY "Users can create financial reports" ON public.financial_reports TO authenticated;
ALTER POLICY "Allow DELETE on warehouse_inventory based on permissions" ON public.warehouse_inventory TO authenticated;
ALTER POLICY "Allow INSERT on warehouse_inventory based on permissions" ON public.warehouse_inventory TO authenticated;
ALTER POLICY "Allow SELECT on warehouse_inventory based on permissions" ON public.warehouse_inventory TO authenticated;
ALTER POLICY "Allow UPDATE on warehouse_inventory based on permissions" ON public.warehouse_inventory TO authenticated;
ALTER POLICY "Users can create inventory items" ON public.warehouse_inventory TO authenticated;
ALTER POLICY "Users can delete inventory items" ON public.warehouse_inventory TO authenticated;
ALTER POLICY "Users can update inventory items" ON public.warehouse_inventory TO authenticated;
ALTER POLICY "Users can view warehouse inventory" ON public.warehouse_inventory TO authenticated;
ALTER POLICY "Allow DELETE on warehouse_transactions based on permissions" ON public.warehouse_transactions TO authenticated;
ALTER POLICY "Allow INSERT on warehouse_transactions based on permissions" ON public.warehouse_transactions TO authenticated;
ALTER POLICY "Allow SELECT on warehouse_transactions based on permissions" ON public.warehouse_transactions TO authenticated;
ALTER POLICY "Allow UPDATE on warehouse_transactions based on permissions" ON public.warehouse_transactions TO authenticated;
ALTER POLICY "Users can create warehouse transactions" ON public.warehouse_transactions TO authenticated;
ALTER POLICY "Users can delete warehouse transactions" ON public.warehouse_transactions TO authenticated;
ALTER POLICY "Users can update warehouse transactions" ON public.warehouse_transactions TO authenticated;
ALTER POLICY "Users can view warehouse transactions" ON public.warehouse_transactions TO authenticated;
ALTER POLICY "Admin can manage all permissions" ON public.user_permissions TO authenticated;
ALTER POLICY "Users can view their own permissions" ON public.user_permissions TO authenticated;
ALTER POLICY "Only admins can view access logs" ON public.customer_access_logs TO authenticated;
ALTER POLICY "Allow DELETE on assignment_orders based on permissions" ON public.assignment_orders TO authenticated;
ALTER POLICY "Allow INSERT on assignment_orders based on permissions" ON public.assignment_orders TO authenticated;
ALTER POLICY "Allow SELECT on assignment_orders based on permissions" ON public.assignment_orders TO authenticated;
ALTER POLICY "Allow UPDATE on assignment_orders based on permissions" ON public.assignment_orders TO authenticated;
ALTER POLICY "Allow DELETE based on permissions" ON public.sales TO authenticated;
ALTER POLICY "Allow INSERT based on permissions" ON public.sales TO authenticated;
ALTER POLICY "Allow SELECT based on permissions" ON public.sales TO authenticated;
ALTER POLICY "Allow UPDATE based on permissions" ON public.sales TO authenticated;