// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwinqajspowvbkvzbbbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3aW5xYWpzcG93dmJrdnpiYmJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTE2MTAsImV4cCI6MjA2NzM4NzYxMH0.dhj2iMZ5IfZUzOW5gAUWyGsnmnTJqMDeA1Rzzh7XXjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});